defaults:
  - _self_
  # - override hydra/launcher: submitit_slurm # Comment this line to run locally

hydra:
  run:
    dir: ./DL_vs_HateSpeech/models/trained_models
  sweep:
    dir: ./DL_vs_HateSpeech/models/trained_models
    subdir: ${model.type}_clip_${model.model_kwargs.clip_model_type}_aug_${train.augmentation}
  sweeper:
    params:
      model.model_kwargs.clip_model_type: "32, 16"
      train.augmentation: True, False

  job:
    chdir: True

  # Comment the following lines to disable the submitit launcher and run locally
  # launcher:
  #   # submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  #   timeout_min: 500
  #   cpus_per_task: null
  #   gpus_per_node: null
  #   tasks_per_node: 1
  #   mem_gb: null
  #   nodes: 1
  #   name: ${hydra.job.name}
  #   _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  #   partition: null
  #   qos: "normal"
  #   comment: null
  #   constraint: null
  #   exclude: null
  #   gres: gpu:1
  #   cpus_per_gpu: 1
  #   gpus_per_task: 1
  #   mem_per_gpu: null
  #   mem_per_cpu: null
  #   account: null
  #   signal_delay_s: 120
  #   max_num_timeout: 0
  #   additional_parameters: {}
  #   array_parallelism: 256
  #   setup: null


model:
  type: "ModelV2"
  model_kwargs:
    clip_model_type: "32"
    hidden_dim: 256
    dropout: 0.1
    output_dim: 1

train:
  batch_size: 32
  epochs: 10
  optimizer: "Adam"
  lr: 1e-4
  augmentation: False
  weight_decay: 0.01
  data_subset: "us_pol"